
version: '3.4'

services:
  opensimserverregionserver:
    image: opensimserverregionserver
    build:
      context: .
      dockerfile: Source/OpenSim.Server.RegionServer/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
